

DROP TABLE IF EXISTS PREDICATION;
CREATE TABLE PREDICATION (
  PREDICATION_ID int NOT NULL,
  SENTENCE_ID int NOT NULL,
  PMID varchar(20) DEFAULT NULL,
  PREDICATE varchar(50) DEFAULT NULL,
  SUBJECT_CUI varchar(255) DEFAULT NULL,
  SUBJECT_NAME varchar(999) DEFAULT NULL,
  SUBJECT_SEMTYPE varchar(50) DEFAULT NULL,
  SUBJECT_NOVELTY int DEFAULT NULL,
  OBJECT_CUI varchar(255) DEFAULT NULL,
  OBJECT_NAME varchar(999) DEFAULT NULL,
  OBJECT_SEMTYPE varchar(50) DEFAULT NULL,
  OBJECT_NOVELTY int DEFAULT NULL,
  FACT_VALUE char(20) DEFAULT NULL,
  MOD_SCALE char(20) DEFAULT NULL,
  MOD_VALUE float DEFAULT NULL,
  PRIMARY KEY (PREDICATION_ID)
);