CREATE INDEX pred_subject_name_idx ON PREDICATION (SUBJECT_NAME);
CREATE INDEX pred_predicate_idx ON PREDICATION (PREDICATE);
CREATE INDEX pred_object_name_idx ON PREDICATION (OBJECT_NAME);

CREATE INDEX pred_subject_cui_idx ON PREDICATION (SUBJECT_CUI);
CREATE INDEX pred_object_cui_idx ON PREDICATION (OBJECT_CUI);
